-- Create database
CREATE DATABASE IF NOT EXISTS BeyondBotDB;

USE BeyondBotDB;

-- Create tables
CREATE TABLE Symbols (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    Symbol VARCHAR(50) NOT NULL UNIQUE
);

CREATE TABLE Timeframes (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    SymbolID INT NOT NULL,
    Timeframe VARCHAR(10) NOT NULL,
    FOREIGN KEY (SymbolID) REFERENCES Symbols(ID) ON DELETE CASCADE
);

CREATE TABLE KLines (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    TimeframeID INT NOT NULL,
    OpenTime DATETIME NOT NULL,
    CloseTime DATETIME NOT NULL,
    OpenPrice DECIMAL(18,8) NOT NULL,
    ClosePrice DECIMAL(18,8) NOT NULL,
    HighPrice DECIMAL(18,8) NOT NULL,
    LowPrice DECIMAL(18,8) NOT NULL,
    Volume DECIMAL(18,8) NOT NULL,
    FOREIGN KEY (TimeframeID) REFERENCES Timeframes(ID) ON DELETE CASCADE
);

CREATE TABLE StrategyCaches (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    KLineID INT NOT NULL,
    StrategyData TEXT,
    FOREIGN KEY (KLineID) REFERENCES KLines(ID) ON DELETE CASCADE
);

CREATE TABLE Orders (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    OrderId VARCHAR(100) NOT NULL UNIQUE,
    Symbol VARCHAR(50) NOT NULL,
    Quantity DECIMAL(18,8) NOT NULL,
    Price DECIMAL(18,8) NOT NULL,
    Status VARCHAR(20) NOT NULL,
    Type VARCHAR(20) NOT NULL,
    Side VARCHAR(10) NOT NULL,
    CreatedAt DATETIME NOT NULL
);